package com.naappe.magneticfielddetector;

import android.app.Activity;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.os.Bundle;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Locale;

public class InvisibleRealityActivity extends Activity implements SensorEventListener {
  private SensorManager sm; private WorldView view;
  @Override protected void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setStatusBarColor(Color.rgb(4,12,23));getWindow().setNavigationBarColor(Color.rgb(4,12,23));getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);sm=(SensorManager)getSystemService(Context.SENSOR_SERVICE);view=new WorldView(this);setContentView(view);}
  @Override protected void onResume(){super.onResume();for(int t:new int[]{Sensor.TYPE_MAGNETIC_FIELD,Sensor.TYPE_ACCELEROMETER,Sensor.TYPE_GYROSCOPE,Sensor.TYPE_LIGHT,Sensor.TYPE_PRESSURE}){Sensor s=sm.getDefaultSensor(t);if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);}}
  @Override protected void onPause(){sm.unregisterListener(this);super.onPause();}
  @Override public void onSensorChanged(SensorEvent e){view.accept(e);}
  @Override public void onAccuracyChanged(Sensor s,int a){}

  static final class WorldView extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),line=new Paint(Paint.ANTI_ALIAS_FLAG); final float[] map=new float[36],baseMap=new float[36]; final Deque<Float> history=new ArrayDeque<>();
    int page,cursor; float mx,my,mz,mag,vib,rot,light=-1,pressure=-1,baseMag,baseVib,baseLight,score; boolean baseline,scanning,hasCompare;
    String explain="Capture a baseline, then scan the same area.";
    WorldView(Context c){super(c);setBackgroundColor(Color.rgb(4,12,23));line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(4);line.setColor(Color.rgb(74,220,188));}
    void accept(SensorEvent e){float[]v=e.values;switch(e.sensor.getType()){case Sensor.TYPE_MAGNETIC_FIELD:mx=v[0];my=v[1];mz=v[2];mag=(float)Math.sqrt(mx*mx+my*my+mz*mz);break;case Sensor.TYPE_ACCELEROMETER:float a=(float)Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);vib=Math.abs(a-9.80665f);break;case Sensor.TYPE_GYROSCOPE:rot=(float)Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);break;case Sensor.TYPE_LIGHT:light=v[0];break;case Sensor.TYPE_PRESSURE:pressure=v[0];break;}process();invalidate();}
    void process(){float md=baseline?Math.abs(mag-baseMag):0,vd=baseline?Math.abs(vib-baseVib):0,ld=baseline&&baseLight>=0&&light>=0?Math.abs(light-baseLight)/Math.max(10,baseLight):0;score=clamp(md*.8f+vd*18+ld*20,0,100);if(!baseline)explain="Capture a baseline, then scan the same area.";else if(md>45&&vib<.6)explain="Strong magnetic change while phone motion is low. Likely nearby stationary magnetic material.";else if(md>20&&vib>.8)explain="Magnetic and mechanical activity changed together. Possible powered or moving equipment.";else if(vib>2)explain="Strong vibration detected without a matching magnetic rise.";else if(ld>1)explain="Large light change dominates this event.";else if(score>35)explain="Multiple sensors differ from baseline; source is not yet classified.";else explain="Current environment closely matches the captured baseline.";history.addLast(score);while(history.size()>100)history.removeFirst();if(scanning&&cursor<36&&rot<.35f&&vib<.45f){map[cursor]=mag;cursor++;scanning=cursor<36;}}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float w=getWidth(),h=getHeight();if(e.getY()>h*.9f){page=Math.max(0,Math.min(3,(int)(e.getX()/(w/4f))));invalidate();return true;}if(page==0&&e.getY()>h*.80f){baseMag=mag;baseVib=vib;baseLight=light;baseline=true;history.clear();}else if(page==1&&e.getY()>h*.78f){if(e.getX()<w/2f){if(cursor>=36){System.arraycopy(map,0,baseMap,0,36);hasCompare=true;for(int i=0;i<36;i++)map[i]=0;cursor=0;}scanning=!scanning;}else{for(int i=0;i<36;i++)map[i]=0;cursor=0;scanning=false;}}else if(page==2&&e.getY()>h*.78f){System.arraycopy(map,0,baseMap,0,36);hasCompare=true;}invalidate();return true;}
    @Override protected void onDraw(Canvas c){super.onDraw(c);header(c);if(page==0)world(c);else if(page==1)scan(c);else if(page==2)compare(c);else explain(c);bottom(c);}
    void header(Canvas c){float w=getWidth(),h=getHeight();p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.056f);c.drawText("Invisible World Scanner",w*.055f,h*.064f,p);p.setFakeBoldText(false);p.setColor(Color.rgb(130,151,177));p.setTextSize(w*.027f);c.drawText("visualize · scan · compare · explain",w*.055f,h*.098f,p);}
    void world(Canvas c){title(c,"LIVE WORLD","Invisible signals rendered as motion and intensity");float w=getWidth(),h=getHeight(),cx=w/2,cy=h*.41f;for(int r=1;r<=5;r++){float rr=w*(.07f+r*.045f);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(fieldColor(mag+r*3));c.drawCircle(cx,cy,rr,p);}p.setStyle(Paint.Style.FILL);for(int i=0;i<18;i++){double a=i*Math.PI*2/18+rot;float rr=w*(.10f+(i%5)*.035f);float x=cx+(float)Math.cos(a)*rr,y=cy+(float)Math.sin(a)*rr;p.setColor(fieldColor(mag+i));c.drawCircle(x,y,6+vib*2,p);}p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.105f);c.drawText(fmt(mag),cx,cy+w*.02f,p);p.setFakeBoldText(false);p.setTextSize(w*.028f);p.setColor(Color.rgb(145,168,193));c.drawText("µT magnetic intensity",cx,cy+w*.075f,p);p.setTextAlign(Paint.Align.LEFT);metric(c,.055f,.63f,.43f,"VIBRATION",fmt(vib),"m/s² residual");metric(c,.515f,.63f,.43f,"LIGHT",light>=0?fmt(light):"--","lux");button(c,baseline?"RECAPTURE BASELINE":"CAPTURE BASELINE");}
    void scan(Canvas c){title(c,"REALITY SCANNER","Hold each point steady; stable samples fill automatically");float w=getWidth(),h=getHeight(),left=w*.055f,top=h*.23f,size=w*.89f,cell=size/6f;for(int i=0;i<36;i++){float l=left+(i%6)*cell,t=top+(i/6)*cell;p.setColor(fieldColor(map[i]));c.drawRoundRect(l+3,t+3,l+cell-3,t+cell-3,10,10,p);if(i==cursor&&cursor<36){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(Color.WHITE);c.drawRoundRect(l+6,t+6,l+cell-6,t+cell-6,8,8,p);p.setStyle(Paint.Style.FILL);}if(map[i]>0){p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(w*.020f);c.drawText(String.format(Locale.US,"%.0f",map[i]),l+cell/2,t+cell*.61f,p);p.setTextAlign(Paint.Align.LEFT);}}metric(c,.055f,.70f,.43f,"PROGRESS",cursor+" / 36",scanning?"automatic capture active":"paused");metric(c,.515f,.70f,.43f,"STABILITY",vib<.45f&&rot<.35f?"READY":"MOVE LESS","vibration + rotation gate");dualButtons(c,scanning?"PAUSE SCAN":"START SCAN","CLEAR");}
    void compare(Canvas c){title(c,"REALITY COMPARE","Difference map between saved and current scans");float w=getWidth(),h=getHeight(),left=w*.055f,top=h*.23f,size=w*.89f,cell=size/6f,max=0,sum=0;for(int i=0;i<36;i++){float d=hasCompare&&map[i]>0?Math.abs(map[i]-baseMap[i]):0;max=Math.max(max,d);sum+=d;float l=left+(i%6)*cell,t=top+(i/6)*cell;p.setColor(diffColor(d));c.drawRoundRect(l+3,t+3,l+cell-3,t+cell-3,10,10,p);if(d>0){p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(w*.020f);c.drawText(String.format(Locale.US,"%.0f",d),l+cell/2,t+cell*.61f,p);p.setTextAlign(Paint.Align.LEFT);}}metric(c,.055f,.70f,.43f,"AVERAGE CHANGE",fmt(sum/36f),"µT across grid");metric(c,.515f,.70f,.43f,"LARGEST CHANGE",fmt(max),"µT hotspot");button(c,"SAVE CURRENT AS REFERENCE");}
    void explain(Canvas c){title(c,"AI EXPLAIN","Transparent reasoning from measured changes");metric(c,.055f,.23f,.89f,"CURRENT INTERPRETATION",explain,"Inference, not certainty");metric(c,.055f,.40f,.43f,"ANOMALY SCORE",fmt(score),"0–100");metric(c,.515f,.40f,.43f,"MAGNETIC DELTA",baseline?fmt(Math.abs(mag-baseMag)):"--","µT");metric(c,.055f,.57f,.43f,"VIBRATION DELTA",baseline?fmt(Math.abs(vib-baseVib)):"--","m/s²");metric(c,.515f,.57f,.43f,"PRESSURE",pressure>0?fmt(pressure):"--","hPa");graph(c);metric(c,.055f,.80f,.89f,"ENGINE","Invisible World 6.0","live visualization + spatial comparison");}
    void graph(Canvas c){float w=getWidth(),h=getHeight(),l=w*.055f,t=h*.72f,r=w*.945f,b=h*.78f;p.setColor(Color.rgb(12,29,49));c.drawRoundRect(l,t,r,b,18,18,p);if(history.size()<2)return;Path path=new Path();int i=0,n=history.size();for(float v:history){float x=l+12+(r-l-24)*i/(n-1f),y=b-8-clamp(v/100,0,1)*(b-t-16);if(i++==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,line);}
    void title(Canvas c,String a,String b){float w=getWidth(),h=getHeight();p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.041f);c.drawText(a,w*.055f,h*.153f,p);p.setFakeBoldText(false);p.setColor(Color.rgb(130,151,177));p.setTextSize(w*.025f);c.drawText(b,w*.055f,h*.197f,p);}
    void metric(Canvas c,float x,float y,float ww,String l,String v,String u){float w=getWidth(),h=getHeight(),left=w*x,top=h*y,width=w*ww,height=h*.105f;p.setColor(Color.rgb(12,29,49));c.drawRoundRect(left,top,left+width,top+height,22,22,p);p.setColor(Color.rgb(125,148,174));p.setTextSize(w*.022f);c.drawText(l,left+17,top+27,p);p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.035f);String z=v.length()>35?v.substring(0,35):v;c.drawText(z,left+17,top+height*.65f,p);p.setFakeBoldText(false);p.setColor(Color.rgb(125,148,174));p.setTextSize(w*.019f);c.drawText(u,left+17,top+height-11,p);}
    void button(Canvas c,String s){float w=getWidth(),h=getHeight(),l=w*.055f,t=h*.835f,ww=w*.89f,hh=h*.05f;p.setColor(Color.rgb(24,99,131));c.drawRoundRect(l,t,l+ww,t+hh,20,20,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.026f);c.drawText(s,l+ww/2,t+hh*.64f,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void dualButtons(Canvas c,String a,String b){float w=getWidth(),h=getHeight(),t=h*.835f;p.setColor(Color.rgb(24,99,131));c.drawRoundRect(w*.055f,t,w*.48f,t+h*.05f,20,20,p);c.drawRoundRect(w*.52f,t,w*.945f,t+h*.05f,20,20,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setFakeBoldText(true);p.setTextSize(w*.025f);c.drawText(a,w*.267f,t+h*.032f,p);c.drawText(b,w*.732f,t+h*.032f,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void bottom(Canvas c){float w=getWidth(),h=getHeight();String[]a={"WORLD","SCAN","COMPARE","EXPLAIN"};for(int i=0;i<4;i++){float l=i*w/4;p.setColor(i==page?Color.rgb(28,103,136):Color.rgb(10,24,41));c.drawRect(l,h*.9f,l+w/4,h,p);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(w*.024f);p.setColor(i==page?Color.WHITE:Color.rgb(130,151,177));c.drawText(a[i],l+w/8,h*.955f,p);}p.setTextAlign(Paint.Align.LEFT);}
    int fieldColor(float v){if(v<=0)return Color.rgb(17,35,54);if(v<50)return Color.rgb(30,115,160);if(v<75)return Color.rgb(60,190,145);if(v<120)return Color.rgb(245,175,65);return Color.rgb(240,75,75);}int diffColor(float d){if(d<=0)return Color.rgb(17,35,54);if(d<10)return Color.rgb(35,105,150);if(d<30)return Color.rgb(65,180,140);if(d<60)return Color.rgb(245,170,60);return Color.rgb(240,70,70);}static float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}static String fmt(float v){return String.format(Locale.US,"%.2f",v);}
  }
}
