const $=s=>document.querySelector(s);let tokenClient,accessToken,lastMailId=localStorage.lastMailId||"";
const cfg=window.APP_CONFIG||{};$("#date").textContent=new Intl.DateTimeFormat("en",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
const esc=s=>(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function card(title,detail){return `<article class="card"><strong>${esc(title)}</strong><p>${esc(detail)}</p></article>`}
function empty(text){return `<div class="empty">${text}</div>`}
function initGoogle(){if(!window.google?.accounts?.oauth2)return setTimeout(initGoogle,300);if(cfg.googleClientId?.startsWith("REPLACE_"))return;$("#setup").hidden=true;tokenClient=google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/calendar.readonly",callback:r=>{accessToken=r.access_token;loadAll()}})}
$("#connect").onclick=()=>tokenClient?tokenClient.requestAccessToken():alert("Google Web OAuth client ID must be configured first.");
async function api(url){const r=await fetch(url,{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadAll(){$("#connect").textContent="Refreshing…";try{await Promise.all([loadMail(),loadEvents()]);$("#connect").textContent="Refresh"}catch(e){$("#connect").textContent="Reconnect Google";alert("Google sync failed. Check OAuth configuration and allowed origins.")}}
async function loadMail(){const list=await api("https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=20&q=in%3Ainbox%20newer_than%3A7d");const messages=await Promise.all((list.messages||[]).map(x=>api(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${x.id}?format=metadata&metadataHeaders=From&metadataHeaders=Subject`)));$("#mailCount").textContent=`${messages.length} messages`;$("#mail").innerHTML=messages.length?messages.map(m=>{const h=Object.fromEntries((m.payload?.headers||[]).map(x=>[x.name,x.value]));return card(h.Subject||"(No subject)",`${h.From||"Unknown sender"} · ${m.snippet||""}`)}).join(""):empty("Inbox is clear");if(messages[0]?.id&&lastMailId&&messages[0].id!==lastMailId)notify("New email",messages[0].snippet||"Open Inbox & Agenda");if(messages[0]?.id){lastMailId=messages[0].id;localStorage.lastMailId=lastMailId}}
async function loadEvents(){const min=new Date(),max=new Date(Date.now()+7*864e5);const url=`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=20&timeMin=${encodeURIComponent(min.toISOString())}&timeMax=${encodeURIComponent(max.toISOString())}`;const data=await api(url),items=data.items||[];$("#eventCount").textContent=`${items.length} events`;$("#events").innerHTML=items.length?items.map(e=>{const d=e.start?.dateTime||e.start?.date;return card(e.summary||"Untitled event",new Intl.DateTimeFormat("en",{weekday:"short",day:"numeric",month:"short",hour:d.includes("T")?"numeric":undefined,minute:d.includes("T")?"2-digit":undefined}).format(new Date(d))) }).join(""):empty("No events in the next 7 days")}
async function notify(title,body){if(Notification.permission==="granted")new Notification(title,{body,icon:"icon.svg"})}
$("#notify").onclick=async()=>{const p=await Notification.requestPermission();if(p==="granted"){notify("Notifications enabled","Keep this installed app open periodically to refresh updates.");$("#notify").textContent="Notifications on"}};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.body.dataset.view=b.dataset.view});
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js");initGoogle();
